import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const api = readFileSync(new URL('../src/api/solonclaw/media.ts', import.meta.url), 'utf8')
const view = readFileSync(new URL('../src/views/solonclaw/ChannelsView.vue', import.meta.url), 'utf8')
const zh = readFileSync(new URL('../src/i18n/locales/zh.ts', import.meta.url), 'utf8')
const en = readFileSync(new URL('../src/i18n/locales/en.ts', import.meta.url), 'utf8')

assert.ok(api.includes('/api/media/${encodeURIComponent(mediaId)}'), 'media detail endpoint should be wrapped')
assert.ok(api.includes('fetchMediaDetail'), 'media detail wrapper should be exported')
assert.ok(view.includes('fetchMediaDetail'), 'channels page should load media detail')
assert.ok(view.includes('mediaDetailOpen'), 'channels page should show media detail drawer')
assert.ok(view.includes('selectedMediaDetail'), 'channels page should retain selected media detail')
const loadMedia = view.slice(view.indexOf('async function loadMedia()'), view.indexOf('async function openMediaDetail'))
assert.match(loadMedia, /catch\s*\(/, 'loadMedia should surface fetchMedia failures instead of rendering an empty cache')
assert.ok(view.includes('mediaLoadError'), 'channels media cache should keep a persistent media load error')
assert.ok(view.includes("!mediaLoadError && mediaItems.length === 0"), 'channels media cache should not show empty state while load failed')
assert.ok(view.includes("t('channels.mediaLoadFailed')"), 'channels media cache should render a localized load failure label')
assert.ok(view.includes('selectedMediaDetail.chat_id'), 'media detail drawer should show chat id')
assert.ok(view.includes('selectedMediaDetail.message_id'), 'media detail drawer should show message id')
assert.ok(view.includes('selectedMediaDetail.mime_type'), 'media detail drawer should show MIME type')
assert.ok(view.includes('selectedMediaDetail.remote_id'), 'media detail drawer should show remote id')
assert.ok(view.includes('selectedMediaDetail.created_at'), 'media detail drawer should show created time')
assert.ok(view.includes('selectedMediaDetail.expires_at'), 'media detail drawer should show expiry time')
assert.ok(zh.includes('媒体缓存'), 'Chinese locale should label media cache')
assert.ok(zh.includes('会话 ID'), 'Chinese locale should label media chat id')
assert.ok(zh.includes('消息 ID'), 'Chinese locale should label media message id')
assert.ok(zh.includes('MIME 类型'), 'Chinese locale should label media MIME type')
assert.ok(zh.includes('远端 ID'), 'Chinese locale should label media remote id')
assert.ok(zh.includes('创建时间'), 'Chinese locale should label media created time')
assert.ok(zh.includes('过期时间'), 'Chinese locale should label media expiry time')
assert.ok(zh.includes('媒体缓存加载失败'), 'Chinese locale should label media load failures')
assert.ok(en.includes('Media cache'), 'English locale should label media cache')
assert.ok(en.includes('Chat ID'), 'English locale should label media chat id')
assert.ok(en.includes('Message ID'), 'English locale should label media message id')
assert.ok(en.includes('MIME type'), 'English locale should label media MIME type')
assert.ok(en.includes('Remote ID'), 'English locale should label media remote id')
assert.ok(en.includes('Created'), 'English locale should label media created time')
assert.ok(en.includes('Expires'), 'English locale should label media expiry time')
assert.ok(en.includes('Failed to load media cache'), 'English locale should label media load failures')
