import assert from 'node:assert/strict'
import { dashboardHashRouteForPath } from '../src/shared/dashboardDirectRoutes.ts'

assert.equal(dashboardHashRouteForPath('/logs'), '#/solonclaw/logs')
assert.equal(dashboardHashRouteForPath('/channels'), '#/solonclaw/channels')
assert.equal(dashboardHashRouteForPath('/cron'), '#/solonclaw/jobs')
assert.equal(dashboardHashRouteForPath('/config'), '#/solonclaw/settings')
assert.equal(dashboardHashRouteForPath('/login'), '#/')
assert.equal(dashboardHashRouteForPath('/status'), '#/solonclaw/diagnostics')
assert.equal(dashboardHashRouteForPath('/diagnostics'), '#/solonclaw/diagnostics')
assert.equal(dashboardHashRouteForPath('/sessions'), '#/solonclaw/runs')
assert.equal(dashboardHashRouteForPath('/analytics'), '#/solonclaw/usage')
assert.equal(dashboardHashRouteForPath('/memory'), '#/solonclaw/persona/journal')
assert.equal(dashboardHashRouteForPath('/workspace'), '#/solonclaw/files')
assert.equal(dashboardHashRouteForPath('/tui-runtime'), '#/solonclaw/tui-runtime')
assert.equal(dashboardHashRouteForPath('/curator'), '#/solonclaw/curator')
assert.equal(dashboardHashRouteForPath('/mcp'), '#/solonclaw/mcp')
assert.equal(dashboardHashRouteForPath('/env'), '#/solonclaw/settings')
assert.equal(dashboardHashRouteForPath('/profiles'), '#/solonclaw/profiles')
assert.equal(dashboardHashRouteForPath('/profiles/new'), '#/solonclaw/profiles/new')
assert.equal(dashboardHashRouteForPath('/profiles/new/'), '#/solonclaw/profiles/new')
assert.equal(dashboardHashRouteForPath('/solonclaw/models'), '#/solonclaw/models')
assert.equal(dashboardHashRouteForPath('/unknown'), '')
