import assert from 'node:assert/strict'
import { dashboardHashRouteForPath } from '../src/shared/dashboardDirectRoutes.ts'

assert.equal(dashboardHashRouteForPath('/logs'), '#/logs')
assert.equal(dashboardHashRouteForPath('/channels'), '#/channels')
assert.equal(dashboardHashRouteForPath('/cron'), '#/jobs')
assert.equal(dashboardHashRouteForPath('/config'), '#/settings')
assert.equal(dashboardHashRouteForPath('/login'), '#/')
assert.equal(dashboardHashRouteForPath('/status'), '#/diagnostics')
assert.equal(dashboardHashRouteForPath('/diagnostics'), '#/diagnostics')
assert.equal(dashboardHashRouteForPath('/sessions'), '#/runs')
assert.equal(dashboardHashRouteForPath('/analytics'), '#/usage')
assert.equal(dashboardHashRouteForPath('/agents'), '#/agents')
assert.equal(dashboardHashRouteForPath('/memory'), '#/persona/journal')
assert.equal(dashboardHashRouteForPath('/workspace'), '#/files')
assert.equal(dashboardHashRouteForPath('/tui-runtime'), '#/tui-runtime')
assert.equal(dashboardHashRouteForPath('/curator'), '#/curator')
assert.equal(dashboardHashRouteForPath('/mcp'), '#/mcp')
assert.equal(dashboardHashRouteForPath('/env'), '#/settings')
assert.equal(dashboardHashRouteForPath('/profiles'), '#/profiles')
assert.equal(dashboardHashRouteForPath('/profiles/new'), '#/profiles/new')
assert.equal(dashboardHashRouteForPath('/profiles/new/'), '#/profiles/new')
assert.equal(dashboardHashRouteForPath('/solonclaw/models'), '')
assert.equal(dashboardHashRouteForPath('/unknown'), '')
