import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const view = readFileSync(new URL('../src/views/solonclaw/GatewaysView.vue', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/stores/solonclaw/gateways.ts', import.meta.url), 'utf8')
const api = readFileSync(new URL('../src/api/solonclaw/gateways.ts', import.meta.url), 'utf8')
const zh = readFileSync(new URL('../src/i18n/locales/zh.ts', import.meta.url), 'utf8')

assert.ok(view.includes('gatewayStore.fetchStatus()'), 'gateway page should keep status refresh')
assert.ok(!view.includes('handleToggle'), 'gateway page should not render unsupported start/stop actions')
assert.ok(!view.includes("from 'antdv-next'") || !view.includes('Button'), 'gateway page should not import a control button for unsupported actions')
assert.ok(!store.includes('startGateway'), 'gateway store should not expose unsupported start action')
assert.ok(!store.includes('stopGateway'), 'gateway store should not expose unsupported stop action')
assert.ok(!api.includes('startGateway'), 'gateway API should not keep a fake start wrapper')
assert.ok(!api.includes('stopGateway'), 'gateway API should not keep a fake stop wrapper')
assert.ok(!api.includes('port: 8080'), 'gateway API should not hard-code the default backend port')
assert.ok(api.includes('__SOLONCLAW_DEV_SERVER_URL__'), 'gateway API should use the Vite backend target when dev proxying')
assert.ok(api.includes('currentGatewayPort()'), 'gateway API should resolve the displayed gateway port through one shared helper')
assert.ok(!zh.includes('查看和控制各消息网关'), 'gateway copy should not imply process control')
assert.ok(store.includes('const loadError = ref<string | null>(null)'), 'gateway store should keep a visible load error')
assert.ok(store.includes('loadError.value = null'), 'gateway refresh should clear stale errors before retrying')
assert.ok(store.includes('loadError.value ='), 'gateway refresh should preserve the failed request message')
assert.ok(store.includes('loadError,'), 'gateway store should expose load errors')
assert.ok(view.includes('onUnmounted'), 'gateway page should clean up its refresh timer')
assert.ok(view.includes('setInterval(refreshStatus, 15000)'), 'gateway page should auto-refresh status')
assert.ok(view.includes('clearInterval(refreshTimer.value)'), 'gateway page should clear the refresh timer on unmount')
const errorIndex = view.indexOf('gatewayStore.loadError')
const emptyIndex = view.indexOf("t('gateways.emptyState')")
assert.ok(errorIndex >= 0, 'gateway page should render load failures')
assert.ok(errorIndex < emptyIndex, 'gateway page should show load failures before the empty state')
