import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const api = readFileSync(new URL('../src/api/solonclaw/diagnostics.ts', import.meta.url), 'utf8')
const view = readFileSync(new URL('../src/views/solonclaw/DiagnosticsView.vue', import.meta.url), 'utf8')
const zh = readFileSync(new URL('../src/i18n/locales/zh.ts', import.meta.url), 'utf8')
const en = readFileSync(new URL('../src/i18n/locales/en.ts', import.meta.url), 'utf8')

assert.ok(api.includes('fetchPluginStatus'), 'diagnostics API should expose plugin status fetch')
assert.ok(api.includes("'/api/plugins/status'"), 'plugin status fetch should call backend endpoint')
assert.ok(view.includes('fetchPluginStatus()'), 'diagnostics view should request plugin status')
assert.ok(view.includes('pluginStatus.value = pluginStatusData'), 'diagnostics view should store plugin status response')
assert.ok(view.includes("t('diagnostics.pluginStatus')"), 'diagnostics view should render plugin status panel')
assert.ok(view.includes('pluginDiagnostics'), 'diagnostics view should normalize plugin diagnostics')
assert.ok(view.includes('pluginLoadedCount'), 'diagnostics view should display loaded plugin count')
assert.ok(view.includes('plugin.version'), 'diagnostics view should render plugin version')
assert.ok(view.includes('plugin.author'), 'diagnostics view should render plugin author')
assert.ok(view.includes('plugin.source'), 'diagnostics view should render plugin source')
assert.ok(view.includes('plugin.enabled'), 'diagnostics view should render plugin enabled state')
assert.ok(view.includes('plugin.auto_load'), 'diagnostics view should render plugin auto-load state')
assert.ok(view.includes('plugin.provides_tools'), 'diagnostics view should render provided tools')
assert.ok(zh.includes("pluginStatus: '插件状态'"), 'Chinese locale should include plugin status label')
assert.ok(zh.includes("pluginVersion: '版本'"), 'Chinese locale should include plugin version label')
assert.ok(zh.includes("pluginAuthor: '作者'"), 'Chinese locale should include plugin author label')
assert.ok(zh.includes("pluginSource: '来源'"), 'Chinese locale should include plugin source label')
assert.ok(zh.includes("pluginEnabled: '启用'"), 'Chinese locale should include plugin enabled label')
assert.ok(zh.includes("pluginAutoLoad: '自动加载'"), 'Chinese locale should include plugin auto-load label')
assert.ok(zh.includes("pluginProvidesTools: '工具'"), 'Chinese locale should include provided tools label')
assert.ok(en.includes("pluginStatus: 'Plugin status'"), 'English locale should include plugin status label')
assert.ok(en.includes("pluginVersion: 'Version'"), 'English locale should include plugin version label')
assert.ok(en.includes("pluginAuthor: 'Author'"), 'English locale should include plugin author label')
assert.ok(en.includes("pluginSource: 'Source'"), 'English locale should include plugin source label')
assert.ok(en.includes("pluginEnabled: 'Enabled'"), 'English locale should include plugin enabled label')
assert.ok(en.includes("pluginAutoLoad: 'Auto-load'"), 'English locale should include plugin auto-load label')
assert.ok(en.includes("pluginProvidesTools: 'Tools'"), 'English locale should include provided tools label')
