import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const apiFile = new URL('../src/api/solonclaw/tuiRuntime.ts', import.meta.url)
const viewFile = new URL('../src/views/solonclaw/TuiRuntimeView.vue', import.meta.url)
const systemNavFile = new URL('../src/components/layout/SystemNavItems.vue', import.meta.url)
const sidebarNavFile = new URL('../src/shared/sidebarNav.ts', import.meta.url)
const router = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../src/components/layout/AppSidebar.vue', import.meta.url), 'utf8')

assert.ok(existsSync(apiFile), 'TUI runtime RPC should have a Web API wrapper')
assert.ok(existsSync(viewFile), 'TUI runtime RPC should have a dashboard page')
assert.ok(existsSync(systemNavFile), 'system sidebar items should stay in a focused component')

const api = readFileSync(apiFile, 'utf8')
const view = readFileSync(viewFile, 'utf8')
const systemNav = readFileSync(systemNavFile, 'utf8')
const sidebarNav = readFileSync(sidebarNavFile, 'utf8')

assert.ok(api.includes("'/api/tui/rpc'"), 'TUI runtime wrapper should call the backend RPC endpoint')
assert.ok(api.includes('fetchTuiRuntimeOverview'), 'TUI runtime wrapper should expose the overview fetch')
assert.ok(!api.includes("'config.set'"), 'dashboard wrapper should not expose generic config writes')
assert.ok(api.includes("'channel.status'"), 'dashboard wrapper should expose channel status refresh')
assert.ok(api.includes("'channel.save'"), 'dashboard wrapper should expose channel setup writes')
assert.ok(api.includes("'channel.qr.start'"), 'dashboard wrapper should expose channel QR start')
assert.ok(api.includes("'channel.qr.get'"), 'dashboard wrapper should expose channel QR polling')
assert.ok(api.includes("'model.save_key'"), 'dashboard wrapper should expose model API key setup')
assert.ok(router.includes('solonclaw.tuiRuntime'), 'router should expose the TUI runtime page')
assert.ok(sidebar.includes('SystemNavItems'), 'sidebar should delegate system entries to the focused component')
assert.ok(systemNav.includes('SYSTEM_NAV_ITEMS'), 'system sidebar component should render the shared system navigation catalog')
assert.ok(sidebarNav.includes("key: 'solonclaw.tuiRuntime'"), 'sidebar should expose the TUI runtime page')
assert.ok(view.includes('fetchTuiRuntimeOverview'), 'TUI runtime page should render the overview')
assert.ok(view.includes('provider.base_url'), 'TUI runtime page should show provider base URL')
assert.ok(view.includes('provider.default_model'), 'TUI runtime page should show provider default model')
assert.ok(view.includes('provider.warning'), 'TUI runtime page should show provider warning')
assert.ok(view.includes('saveModelApiKey'), 'TUI runtime page should save provider API keys')
assert.ok(view.includes('saveChannelConfig'), 'TUI runtime page should save channel required fields')
assert.ok(view.includes('channelEnabledValue'), 'TUI runtime page should expose the channel enabled switch')
assert.ok(view.includes('setChannelEnabledValue'), 'TUI runtime page should submit channel enabled state')
assert.ok(view.includes('startChannelQr'), 'TUI runtime page should start channel QR setup')
